name: Build Collator

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

  push:
    branches: [zombienet-cicd]

env:
  GCP_PROJECT_ID: "paid-network-202104"
  ZOMBIENET_VERSION: "v1.2.38"
  POLKADOT_VERSION: "v0.9.20"

jobs:
  compute-image-tag:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ env.IMAGE_TAG }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Git SHA
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Use latest
        if: ${{ github.event_name == 'push' }}
        run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV

  # TODO: Build Base image when dockerfile.base file changes
  build-collator-image:
    runs-on: ubuntu-latest
    needs: [compute-image-tag]
    steps:
      - uses: actions/checkout@v2
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker credentials
        run: gcloud auth configure-docker

      #- name: Build a new collater build image
      #  run: |
      #    docker build -f docker/Dockerfile.build -t gcr.io/${{ env.GCP_PROJECT_ID }}/collator:build .

      #- name: Build a new image for Zombienet
      #  run: |
      #    docker build -f docker/Dockerfile.zombie -t gcr.io/${{ env.GCP_PROJECT_ID }}/collator:z2 .

      #- name: Push Zombienet collator image
      #  run: |
      #    docker push gcr.io/${{ env.GCP_PROJECT_ID }}/collator:z2

      #- name: Start minikube
      #  uses: medyagh/setup-minikube@master
      #- name: Test local cluster
      #  run: kubectl get pods -A

      - name: Start minikube
        run: minikube start

      - name: Install Zombienet
        run: |
          wget https://github.com/paritytech/zombienet/releases/download/${{ env.ZOMBIENET_VERSION }}/zombienet-linux
          chmod +x ./zombienet-linux

      - name: Run Zombienet tests against the new Zombienet collator image
        run: |
          export POLKADOT_VERSION=${{env.POLKADOT_VERSION}}
          export COLLATOR_VERSION=z2
          ./zombienet-linux -p kubernetes test zombienet/0001-small-network.feature

      #- name: Build image
      #  run: docker build -f docker/Dockerfile -t paidnetwork/collator .

      #- name: Tag & Publish
      #  run: |
      #    docker tag paidnetwork/collator gcr.io/${{ env.GCP_PROJECT_ID }}/collator:${{ needs.compute-image-tag.outputs.IMAGE_TAG }}
      #    docker push gcr.io/${{ env.GCP_PROJECT_ID }}/collator:${{ needs.compute-image-tag.outputs.IMAGE_TAG }}
